# -*- coding: utf-8 -*-
"""elkom11.1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wGoBDeUQEJhCtk-WZcE0O_ko3QuuWpdn
"""

import sys

data = {}  # Assuming 'data' is a dictionary to store student data

def awal():
    nama_file = input('Masukkan nama File: ')
    if nama_file == 'contoh.txt':
        baca_data_file()
        main()
    else:
        print("File tidak ditemukan")

def baca_data_file():
    try:
        with open('contoh.txt', 'r') as file:
            for line in file:
                values = line.strip().split()
                nama_mahasiswa = values[0]
                nilai_praktikum = list(map(int, values[1:]))
                data[nama_mahasiswa] = nilai_praktikum
    except FileNotFoundError:
        print("File 'contoh.txt' tidak ditemukan.")

def baca_data():
    print("Daftar Mahasiswa:")
    for nama_mahasiswa, nilai_praktikum in data.items():
        print(f"{nama_mahasiswa} {' '.join(map(str, nilai_praktikum))}")

def mencari_rata_rata_mahasiswa():
    nama = input("Masukkan nama mahasiswa: ")
    if nama in data:
        rata_rata = sum(data[nama]) / len(data[nama])
        print(f"Rerata nilai praktikum {nama} = {rata_rata:.2f}")
    else:
        print(f"Mahasiswa dengan nama {nama} tidak ditemukan.")

def update_nilai_praktikum():
    nama = input("Masukkan nama mahasiswa: ")
    if nama in data:
        praktikum_ke = int(input("Ingin update nilai praktikum ke-: "))
        if praktikum_ke in range(1, len(data[nama])+1):
            nilai_baru = int(input(f"Nilai baru untuk Praktikum {praktikum_ke}: "))
            data[nama][praktikum_ke-1] = nilai_baru
            print(f"Nilai praktikum {praktikum_ke} mahasiswa {nama} berhasil diupdate.")
        else:
            print("Pilihan praktikum tidak valid.")
    else:
        print(f"Mahasiswa dengan nama {nama} tidak ditemukan.")

def simpan():
    try:
        with open("contoh.txt", "w") as text_file:
            for nama_mahasiswa, nilai_praktikum in data.items():
                line = f"{nama_mahasiswa} {' '.join(map(str, nilai_praktikum))}\n"
                text_file.write(line)
        print("Perubahan berhasil disimpan")
    except Exception as e:
        print(f"Terjadi kesalahan saat menyimpan perubahan: {e}")

def main():
    while True:
        print('''
        [MENU]
        1. Baca Data
        2. Mencari Nilai Rata-Rata Praktikum Mahasiswa
        3. Update Nilai Praktikum Mahasiswa
        4. Simpan Perubahan nilai
        5. Exit
        ''')
        choose_menu = int(input('Silakan Pilih: '))

        if choose_menu == 1:
            baca_data()
        elif choose_menu == 2:
            mencari_rata_rata_mahasiswa()
        elif choose_menu == 3:
            update_nilai_praktikum()
        elif choose_menu == 4:
            simpan()
        elif choose_menu == 5:
            sys.exit(0)
        else:
            print("Pilihan tidak valid. Silakan pilih lagi.")

if __name__ == '__main__':
    awal()
    main()