# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jp7lpxZWvMrP1QBVR5DLemSC3-mgt-Jh
"""

import sys

file_name = input("Masukkan nama file: ")

def baca_data():
    print("Daftar Nama dan Nilai")
    for line in data:
        dataline = line.strip().split(' ')
        scores = dataline[-3:]
        nama = ' '.join(dataline[:-3])
        print(f"{nama} = {' '.join(scores)}")

def nilai_rata_rata():
    input_nama = input("Masukkan nama mahasiswa: ")
    for line in data:
        dataline = line.strip().split(' ')
        scores = map(int, dataline[-3:])
        nama = ' '.join(dataline[:-3])
        if input_nama == nama:
            rata_rata = sum(scores) / len(scores)
            print(f"{nama} = {' '.join(map(str, scores))} (rata_rata: {rata_rata:.2f})")

def ubah_nilai():
    print("Update Nilai")
    input_nama = input("Masukkan nama mahasiswa: ")
    nilai_ke = int(input("Update nilai praktikum ke-: "))
    nilai_baru = int(input("Masukkan nilai baru: "))
    for i, line in enumerate(data):
        dataline = line.strip().split(' ')
        scores = list(map(int, dataline[-3:]))
        nama = ' '.join(dataline[:-3])
        if input_nama == nama:
            nilailama = scores[nilai_ke - 1]
            scores[nilai_ke - 1] = nilai_baru
            data[i] = f"{nama} {' '.join(map(str, scores))}\n"
            print(f"Berhasil Diupdate!")
            updates.append(f"[{nama}] Update nilai prak {nilai_ke} | {nilailama} >> {nilai_baru}")

def simpan_data():
    with open(file_name, 'w') as file:
        file.write(''.join(data))
    print("Perubahan berhasil disimpan.")

def keluar():
    sys.exit(0)

def main():
    print(f"""\t======{file_name}======
    1. Baca Data
    2. Mencari Rata-Rata Nilai Praktikum
    3. Update Nilai Praktikum
    4. Simpan Perubahan Nilai
    5. Keluar""")

    menu = input("Mau yang mana: ")

    try:
        menu = int(menu)
    except ValueError:
        print("Masukkan angka sebagai pilihan.")
        return

    if menu == 1:
        baca_data()
    elif menu == 2:
        nilai_rata_rata()
    elif menu == 3:
        ubah_nilai()
    elif menu == 4:
        simpan_data()
    elif menu == 5:
        keluar()
    else:
        print("Pilihan tidak valid.")

if __name__ == "__main__":
    with open(file_name, 'r') as file:
        data = file.readlines()

    updates = []
    main()